### ISSUE TITLE
dm_timeEntries.r week start uses the wrong days

### ISSUE THREAD

**Issue by evandowney** [propellerpdx/dataPipeline#7]
dm_timeEntries.r uses the wrong start days of week.

Per documentation, lubridate uses the ISO standard for start of week
https://lubridate.tidyverse.org/reference/day.html
https://en.wikipedia.org/wiki/ISO_week_date

1 = Monday & 7 = Sunday.

So shift so that 1 is *5 and 5 is *1

**Comment by mark-druffel** [comment]
I don't think this is the issue, I think the issue is that if a person does not work on their first day on the bench - I don't capture a start date and they don't get a cap (e.g. it shows a cap of NA).

**Comment by mark-druffel** [comment]
This was not the issue, the issue was that if the person didn't work the first day they were on the bench it didn't carry forward the bench_start_date. Fixed with pull request #8.
